import type { OverviewCopyKey } from "./overview-view"

export const overviewEnglish = {
  "puff.overview.title": "Project overview",
  "puff.overview.people": "People and agents",
  "puff.overview.statedFocus": "Stated focus",
  "puff.overview.agentReport": "Agent reported work",
  "puff.overview.projectWork": "Project work",
  "puff.overview.privateWork": "Your other sessions",
  "puff.overview.privateNotice": "These sessions stay outside this project's overview until you select them for sharing.",
  "puff.overview.reportedResults": "Reported results",
  "puff.overview.inspectSource": "Inspect source",
  "puff.overview.relatedWork": "Related work",
  "puff.overview.reportedCompletion": "Reported complete · inspect before reuse",
  "puff.overview.noSummary": "No source-backed report yet",
  "puff.overview.noFocus": "No focus stated",
  "puff.overview.details": "Details and sources",
  "puff.overview.blocker": "Blocker",
  "puff.overview.workDone": "Reported done",
  "puff.overview.executionUnknown": "Agent state unknown",
  "puff.overview.current": "Current report",
  "puff.overview.stale": "Report out of date",
  "puff.overview.possibleOverlap": "Possibly related · inspect first",
  "puff.overview.deliberateAlternative": "Deliberate alternative",
  "puff.overview.inspect": "Inspect",
  "puff.overview.continue": "Continue session",
  "puff.overview.reuse": "Review for reuse",
  "puff.overview.separate": "Keep approaches separate",
  "puff.overview.unavailable": "These choices need a confirmed project decision.",
  "puff.overview.noResults": "No source-linked results reported yet.",
  "puff.overview.noAttention": "No known decisions waiting.",
  "puff.overview.noSessions": "No sessions have been shared with this project yet.",
  "puff.overview.noPrivateSessions": "No other sessions to show.",
  "puff.overview.toolPermission": "Tool permission requested",
  "puff.overview.needsAttention": "Needs attention",
  "puff.overview.updatedAt": "Updated at",
  "puff.overview.workQueued": "Work queued",
  "puff.overview.workActive": "Reported in progress",
  "puff.overview.workBlocked": "Reported blocked",
  "puff.overview.workIdle": "Reported idle",
  "puff.overview.executionQueued": "Agent queued",
  "puff.overview.executionRunning": "Agent working",
  "puff.overview.executionWaiting": "Waiting for tool approval",
  "puff.overview.executionCompleted": "Run completed",
  "puff.overview.executionFailed": "Run failed",
  "puff.overview.executionRecovery": "Delivery needs reconciliation",
  "puff.overview.executionReserved": "Agent preparing",
  "puff.overview.executionCancelling": "Agent stopping",
  "puff.overview.executionCancelled": "Run cancelled",
  "puff.overview.sourceLabel": "Inspect source event {{eventId}}",
  "puff.overview.ownerLabel": "Agent owner: {{owner}}",
  "puff.overview.startedByLabel": "Started by {{creator}}",
  "puff.overview.noOwnedSessions": "No agent sessions attributed yet.",
  "puff.overview.noCurrentReport": "No current report",
  "puff.overview.lastReported": "Last reported · out of date",
  "puff.overview.openSession": "Open session",
  "puff.overview.openSessionLabel": "Open {{title}}",
  "puff.overview.connectTitle": "Bring your project into view",
  "puff.overview.connectHint": "Connect your team account to see selected project work and its sources.",
  "puff.overview.connectAction": "Connect team",
  "puff.overview.noProject": "No project is available to this member yet.",
  "puff.overview.loadError": "The current overview could not be confirmed. Refresh to try again.",
  "puff.overview.loading": "Loading project overview…",
} as const satisfies Record<`puff.overview.${OverviewCopyKey}`, string>
