export const simulationEnglish = {
  "puff.simulation.rail.wf01A": "Exploring compact navigation.",
  "puff.simulation.rail.wf01B": "Exploring expanded navigation.",
  "puff.simulation.rail.wf02A": "Reported a focus constraint.",
  "puff.simulation.rail.wf02BSource": "Planning expanded navigation.",
  "puff.simulation.rail.wf02BAdmitted": "A’s finding is staged for B.",
  "puff.simulation.rail.wf02BPromoted": "A’s finding is visible to B.",
  "puff.simulation.rail.wf02BUsed": "Added a focus-return check.",
  "puff.simulation.rail.wf03OverlapA": "Investigating search reset.",
  "puff.simulation.rail.wf03OverlapB": "Investigating search reset.",
  "puff.simulation.rail.wf03Db": "Mapped migration pages and links.",
  "puff.simulation.rail.wf03Ui": "Reviewing project navigation.",
  "puff.simulation.rail.localDemo": "Local demo",
  "puff.simulation.rail.about": "About this demo",
  "puff.simulation.rail.guideHint": "Choose an example, then open its demo controls if needed.",
  "puff.simulation.rail.showControls": "Scenario details and controls",
  "puff.simulation.taskStart.title": "Start with what needs doing",
  "puff.simulation.taskStart.newTask": "New demo task",
  "puff.simulation.taskStart.intro": "Try a task. This local example checks one named completed work item before any new agent starts.",
  "puff.simulation.taskStart.close": "Close",
  "puff.simulation.taskStart.switchProject": "This completed-work example belongs to the WF03 project.",
  "puff.simulation.taskStart.openProject": "Open example project",
  "puff.simulation.taskStart.prompt": "What do you want to work on?",
  "puff.simulation.taskStart.placeholder": "Map database migration navigation",
  "puff.simulation.taskStart.check": "Check prior work",
  "puff.simulation.taskStart.useExample": "Use example task",
  "puff.simulation.taskStart.checking": "Checking the exact completed-work source…",
  "puff.simulation.taskStart.unavailable": "The completed-work source could not be verified. No completion warning is shown.",
  "puff.simulation.taskStart.noMatch": "No named completed-work match in this demo for that task. No agent was started.",
  "puff.simulation.taskStart.separateSelected": "Separate work selected for this demo draft. No agent was started or redirected.",
  "puff.simulation.taskStart.remainingSelected": "Selected “{{task}}” as a demo draft. No agent was started.",
  "puff.simulation.taskStart.completedLabel": "SOURCE-BACKED DEMO RESULT",
  "puff.simulation.taskStart.alreadyDone": "{{person}} already reported this complete",
  "puff.simulation.taskStart.sourceSession": "Reported in {{title}}",
  "puff.simulation.taskStart.exactSource": "Exact source and result text",
  "puff.simulation.taskStart.inspect": "Inspect result",
  "puff.simulation.taskStart.continue": "Continue existing session",
  "puff.simulation.taskStart.separate": "Work separately",
  "puff.simulation.taskStart.remainingTitle": "Useful remaining tasks",
  "puff.simulation.taskStart.remainingIntro": "These unfinished checks are named in the completed result. Choose one to draft next; nothing starts automatically.",
  "puff.simulation.taskStart.choose": "Choose this task",
  "puff.simulation.taskStart.inspectBasis": "Inspect basis",
  "puff.simulation.banner": "SIMULATED",
  "puff.simulation.bannerDetail": "Local demonstration only. No Flower or OpenCode agent receives this scenario data.",
  "puff.simulation.connect": "Connect simulated workflows",
  "puff.simulation.connectHint": "Uses a local demo service on 127.0.0.1:4187 and public synthetic account Alice.",
  "puff.simulation.guide": "Try the three workflows",
  "puff.simulation.wf01": "WF01 · Alternatives",
  "puff.simulation.wf02": "WF02 · Finding to use",
  "puff.simulation.wf03": "WF03 · Overlap check",
  "puff.simulation.wf01Explanation": "Two approaches stay separate. The unshared session is excluded from project reads.",
  "puff.simulation.wf02Explanation": "Step through a canned source finding, admission, promotion, and use. Each stage is simulated.",
  "puff.simulation.wf03Explanation": "A possible duplicate is distinct from similar wording across unrelated topics.",
  "puff.simulation.current": "Current scenario",
  "puff.simulation.switch": "Show {{name}}",
  "puff.simulation.source": "Source finding",
  "puff.simulation.admitted": "Simulated admission",
  "puff.simulation.promoted": "Simulated promotion",
  "puff.simulation.used": "Simulated use",
  "puff.simulation.done": "Shown in fixture",
  "puff.simulation.next": "Next fixture step",
  "puff.simulation.pending": "Not yet shown",
  "puff.simulation.receiptDetails": "Fixture receipt",
  "puff.simulation.inspectSource": "Inspect exact A source",
  "puff.simulation.openTarget": "Open target B session",
  "puff.simulation.advance": "Advance simulated stage",
  "puff.simulation.reset": "Reseed all demo scenarios",
  "puff.simulation.resetHint": "Restores the original local fixture. You can replay the stages.",
  "puff.simulation.actionError": "The simulator did not confirm this change. The current stage is unchanged.",
  "puff.simulation.readOnly": "Demo steps are controlled here. Agent instructions and approvals are unavailable in this simulation.",
  "puff.simulation.unknownActor": "Demo participant",
  "puff.simulation.overlap": "Possible duplicate investigation",
  "puff.simulation.overlapDetail": "The same selected topic may need a source-backed review. No session is stopped or merged.",
  "puff.simulation.unrelated": "Unrelated similar wording",
  "puff.simulation.unrelatedDetail": "Different selected topics produce no actionable cross-session finding.",
  "puff.simulation.noFinding": "No cross-session finding is recorded for this pair.",
  "puff.simulation.alternative": "Deliberate alternatives",
  "puff.simulation.alternativeDetail": "Both experiments remain active and independent. Neither is chosen as the winner.",
  "puff.simulation.privateExcluded": "Unshared work stays outside this project view.",
  "puff.simulation.replay": "Replay this scenario",
} as const
