export const simulationEnglish = {
  "puff.simulation.banner": "SIMULATED",
  "puff.simulation.bannerDetail": "Local demonstration only. No Flower or OpenCode agent receives this scenario data.",
  "puff.simulation.connect": "Connect simulated workflows",
  "puff.simulation.connectHint": "Uses a local demo service on 127.0.0.1:4187 and public synthetic account Alice.",
  "puff.simulation.guide": "Try the three workflows",
  "puff.simulation.wf01": "WF01 · Alternatives",
  "puff.simulation.wf02": "WF02 · Finding to use",
  "puff.simulation.wf03": "WF03 · Overlap check",
  "puff.simulation.wf01Explanation": "Two approaches stay separate. The unshared session is excluded from project reads.",
  "puff.simulation.wf02Explanation": "Step through a canned source finding, admission, promotion, and use. Each stage is simulated.",
  "puff.simulation.wf03Explanation": "A possible duplicate is distinct from similar wording across unrelated topics.",
  "puff.simulation.current": "Current scenario",
  "puff.simulation.switch": "Show {{name}}",
  "puff.simulation.source": "Source finding",
  "puff.simulation.admitted": "Simulated admission",
  "puff.simulation.promoted": "Simulated promotion",
  "puff.simulation.used": "Simulated use",
  "puff.simulation.done": "Shown in fixture",
  "puff.simulation.next": "Next fixture step",
  "puff.simulation.pending": "Not yet shown",
  "puff.simulation.receiptDetails": "Fixture receipt",
  "puff.simulation.inspectSource": "Inspect exact A source",
  "puff.simulation.openTarget": "Open target B session",
  "puff.simulation.advance": "Advance simulated stage",
  "puff.simulation.reset": "Reseed all demo scenarios",
  "puff.simulation.resetHint": "Restores the original local fixture. You can replay the stages.",
  "puff.simulation.actionError": "The simulator did not confirm this change. The current stage is unchanged.",
  "puff.simulation.readOnly": "Demo steps are controlled here. Agent instructions and approvals are unavailable in this simulation.",
  "puff.simulation.unknownActor": "Demo participant",
  "puff.simulation.overlap": "Possible duplicate investigation",
  "puff.simulation.overlapDetail": "The same selected topic may need a source-backed review. No session is stopped or merged.",
  "puff.simulation.unrelated": "Unrelated similar wording",
  "puff.simulation.unrelatedDetail": "Different selected topics produce no actionable cross-session finding.",
  "puff.simulation.noFinding": "No cross-session finding is recorded for this pair.",
  "puff.simulation.alternative": "Deliberate alternatives",
  "puff.simulation.alternativeDetail": "Both experiments remain active and independent. Neither is chosen as the winner.",
  "puff.simulation.privateExcluded": "Unshared work stays outside this project view.",
  "puff.simulation.replay": "Replay this scenario",
} as const
